services:
  - type: web
    name: telegram-bot-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
